version: 2.1
jobs:
  test:
    parameters:
      ruby:
        description: "Ruby version"
        default: "2.7.5"
        type: "string"
    docker:
      - image: cimg/ruby:<< parameters.ruby >>
    steps:
      - checkout
      - run:
          name: Run the default task
          command: |
            gem install bundler -v 2.2.3
            bundle install
            bundle exec rake

workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              ruby: ["2.7.5", "3.0.0"]
